---
- name: Common setup for all nodes
  hosts: k8s_cluster
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install basic packages
      ansible.builtin.apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - gnupg2
        state: present

    - name: Set timezone to UTC
      ansible.builtin.timezone:
        name: Etc/UTC